services:
  db:
    image: postgres:16
    container_name: room_reservation_db
    environment:
      POSTGRES_DB: room_reservation
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_secret
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - room_reservation_data:/var/lib/postgresql/data

volumes:
  room_reservation_data:
